/** This file is auto generated and MUST NOT be manually modified **/
#ifndef __NEXUS_HEADER__
#define __NEXUS_HEADER__

#include "NxsDefine.h"
#include "base/CString.hpp"
#include "base/Math.hpp"
#include "base/String.hpp"
#include "base/SystemClock.hpp"
#include "base/Utils.hpp"
#include "debug/Debug.hpp"
#include "graphics/Color.hpp"
#include "graphics/GraphicsConst.h"
#include "graphics/RenderCommand.hpp"
#include "graphics/RenderSystem.hpp"
#include "graphics/Shader.hpp"
#include "graphics/Vertex.hpp"
#include "graphics/VertexBuffer.hpp"
#include "graphics/opengl/GLRenderSystem.hpp"
#include "graphics/opengl/GLShader.hpp"
#include "graphics/opengl/GLVertexBuffer.hpp"
#include "graphics/opengl/NxsGL.h"
#include "io/Data.hpp"
#include "io/File.hpp"
#include "os/Path.hpp"
#include "pattern/Factory.hpp"
#include "pattern/Singleton.hpp"
#include "pattern/StateMachine.hpp"
#include "platform/Application.hpp"
#include "resource/Mesh.hpp"
#include "resource/MeshResourceManager.hpp"
#include "resource/OBJMesh.hpp"
#include "resource/ResourceManager.hpp"
#include "scene/Node.hpp"
#include "scene/Scene.hpp"
#include "scene/Transform.hpp"

#endif // __NEXUS_HEADER__