set(TARGET_NAME nexus-task)
set(NXS_TASK_PUBLIC_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

file(GLOB_RECURSE NXS_TASK_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
)

add_library(${TARGET_NAME} STATIC ${NXS_TASK_SOURCES})
target_include_directories(${TARGET_NAME}
    PUBLIC ${NXS_TASK_PUBLIC_HEADER_DIR}
    PUBLIC ${NXS_PUBLIC_INCLUDE_DIR}
    PUBLIC ${ENGINE_INCLUDE_DIR}
    PUBLIC ${ENGINE_3RD_PARTY_DIR}

    PRIVATE "${REMOTERY_SOURCE_DIR}"
)

target_link_libraries(${TARGET_NAME}
    PUBLIC nexus-time
)
