set(TARGET_NAME nexus-time)
set(NXS_TIME_PUBLIC_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

file(GLOB_RECURSE NXS_TIME_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
)

add_library(${TARGET_NAME} STATIC ${NXS_TIME_SOURCES})
target_include_directories(${TARGET_NAME}
    PUBLIC ${NXS_TIME_PUBLIC_HEADER_DIR}
    PUBLIC ${ENGINE_INCLUDE_DIR}
    PUBLIC ${ENGINE_3RD_PARTY_DIR}
)

target_link_libraries(${TARGET_NAME}
    PRIVATE SDL3::SDL3
)
