macro(add_example_executable TARGET)
    cmake_parse_arguments(ARG "" "" "SOURCES;DATAFILES" ${ARGN})
    if(AST_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown argument(s): ${ARG_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "add_example_executable needs at least one source")
    endif()

    add_executable(${TARGET} ${ARG_SOURCES})
    target_link_libraries(${TARGET} nexus-engine)
endmacro()

add_example_executable(example-01 SOURCES example-01-HelloWorld.cpp)
add_example_executable(example-02 SOURCES example-02-Cubes.cpp)
add_example_executable(example-03 SOURCES example-03-Texture.cpp)
add_example_executable(example-04 SOURCES example-04-Lighting.cpp)
add_example_executable(example-05 SOURCES example-05-ModelLoading.cpp)