set(TARGET_NAME nexus-reflection)
set(NXS_REFLECTION_PUBLIC_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

file(GLOB_RECURSE NXS_REFLECTION_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
)

add_library(${TARGET_NAME} STATIC ${NXS_REFLECTION_SOURCES})
target_include_directories(${TARGET_NAME}
    PUBLIC ${NXS_REFLECTION_PUBLIC_HEADER_DIR}
    PUBLIC ${ENGINE_INCLUDE_DIR}
    PUBLIC ${ENGINE_3RD_PARTY_DIR}
)

target_link_libraries(${TARGET_NAME}
    PUBLIC nexus-core
    PUBLIC nexus-serialize
)
